# Site settings
author: Nancy Jackson
title: Choosing Code
header-img: img/home-bg.png
email: nbjackson23@gmail.com
copyright_name: Nancy Jackson
description: > # this means to ignore newlines until "baseurl:"
  A Complete Turn Around
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  nbjackson23

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
